"""Add blacklist_requests and redis_updates columns

Revision ID: 1d72843134b6
Revises:
Create Date: 2025-07-28 09:40:56.179418

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1d72843134b6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_usage_tracking", sa.Column("blacklist_requests", sa.Integer(), nullable=True)
    )
    op.add_column("api_usage_tracking", sa.Column("redis_updates", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_usage_tracking", "redis_updates")
    op.drop_column("api_usage_tracking", "blacklist_requests")
    # ### end Alembic commands ###
